baseURL = "https://metaiot.group/" # 请替换为你的实际域名
languageCode = "en-us"
title = "MetaIoT"
theme = [] # 我们手动重构，不使用第三方主题包

# 启用内联 HTML (因为你的 Markdown 可能包含 HTML 标签)
[markup.goldmark.renderer]
unsafe = true


[markup.highlight]
style = "monokai" # Rouge 的替代品，风格可选
lineNos = false

# 全局参数
[params]
subtitle = "Welcome to MetaIoT Lab."
description = "We create the next generation of intelligent wireless systems for communication and sensing with applications in autonomous systems, mixed reality, and IoT."
header_image = "images/background.webp"
footer_image = "images/background.webp"
google_scholar = "YkD8hs0AAAAJ"
[params.links]
    email = "mailto:wangw@whu.edu.cn" 
    google-scholar = "https://scholar.google.com/citations?user=YkD8hs0AAAAJ"
    github = "https://github.com/MetaIoT-WHU"
    youtube = "https://www.youtube.com/channel/WeiWANGWilliam"


[menu]
